spring:
  datasource:
    username: protogen_user3
    password: protogen_user3_123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/protogen?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=CTT

